services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    ports:
      - 8080:4180
    env_file:
      - ./.env
  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app/app.py:/opt/app/app.py
    env_file:
      - ./.env
